# -*- coding: utf-8 -*-
"""streamlit 2app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2IRRe1D54O0i7XKUoG7WeEBJvujG5ri
"""

import streamlit as st
import openai

# Initialize OpenAI - ADD YOUR KEY HERE
openai.api_key = "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"  # <<< REPLACE WITH YOUR KEY

st.title("🚀 YOUR AI SALES AGENT")
st.subheader("Paste LinkedIn URL below")

linkedin_url = st.text_input("", value="https://www.linkedin.com/in/saleswithdhruvtomar/")
generate_clicked = st.button("Create Personalized Email")

if generate_clicked:
    prompt = f"""
    Create a personalized sales email for a prospect with LinkedIn profile: {linkedin_url}.
    Include:
    - Reference to their specific role/industry
    - 1 personalized compliment based on their profile
    - Clear call-to-action
    """

    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[{"role": "user", "content": prompt}]
    )

    email_draft = response.choices[0].message.content

    st.success("AI DRAFT GENERATED!")
    st.markdown(f"**Subject:** Quick question about your work at {linkedin_url.split('/in/')[-1].split('/')[0].title()}")
    st.write(email_draft)
    st.caption("Real-time personalization active!")